version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install ecs-deploy
          command: sudo npm install -g ecs-deploy

      - run:
          name: Runing unit tests
          command: yarn test --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "test-results/Jest/js-test-results.xml"

      - store_test_results:
          path: test-results

      - run:
          name: Build
          command: yarn clean && yarn build

      - setup_remote_docker

      - run:
          name: Build docker image
          command: docker build -t $AWS_ECR_URI:$CIRCLE_SHA1 -f production.Dockerfile .

      - run:
          name: Push to ECR
          command: |
            docker push $AWS_ECR_URI:$CIRCLE_SHA1

      - run:
          name: Deploy image
          command: REGION=us-east-1 CLUSTER=js-workshop SERVICE=js-workshop-le-api CONTAINER=app IMAGE=$AWS_ECR_URI IMAGE_TAG=$CIRCLE_SHA1 ecs-deploy

